dist: trusty
sudo: required

before_install:
  # Install Ansinle
  - sudo apt-get install software-properties-common -y
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible -y
  # Create local SSH key
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  # Debug info
  - cat /etc/default/lxc-net
  - cat /etc/lxc/default.conf
  - ip addr show

script:
  - ./lab setup
  - ./lab teardown
